### ISSUE TITLE
Add Docker pre-commit hook

### ISSUE THREAD

**Issue by allie-jo** [clj-kondo/clj-kondo#1863]
**Is your feature request related to a problem? Please describe.**
We've been using clj-kondo as a pre-commit hook in many of our projects, but in order to preempt users from having to install all of the dependencies for each pre-commit hook (including clj-kondo) we've been using Docker images instead. Because we do this manually using the `local` section of our pre-commit-config, we have to update the version manually. It would be great if the repo provided a docker hook directly so we can have CI run `pre-commit autoupdate` to update versions periodically automatically. 

**Describe the solution you'd like**
Add a Docker hook in `.pre-commit-hooks.yaml`, pinned to the currently published docker version of clj-kondo. We've been using:

```yaml
  - id: clj-kondo-docker
    name: clj-kondo (via docker)
    entry: cljkondo/clj-kondo:2022.11.03
    args: [clj-kondo, --lint]
    language: docker_image
    types: [clojure]
```

In our projects successfully for a while now. Would need to templatize `.pre-commit-hooks.yaml` but otherwise is a small change. 

**Additional context**
How we're using clj-kondo in our pre-commits currently:

```yaml
repos:
  ...
  ...
  - repo: local
    hooks:
      - id: clj-kondo
        name: clj-kondo (via docker)
        entry: cljkondo/clj-kondo:2022.11.03
        args: [clj-kondo, --lint]
        language: docker_image
        types: [clojure]
```

Happy to do this PR myself :)

**Comment by borkdude** [comment]
Does this mean that current users of the config suddenly will have to use Docker?

**Comment by allie-jo** [comment]
nope! it's just another option.
if you wanna use the current executable based hook
```yaml
repos:
  - repo: https://github.com/clj-kondo/clj-kondo.git
    rev: v2022.11.02
    hooks:
      - id: clj-kondo
```
and if you wanna use the docker version
```yaml
repos:
  - repo: https://github.com/clj-kondo/clj-kondo.git
    rev: v2022.11.02
    hooks:
      - id: clj-kondo-docker
```
